In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("Compute_allocations_transformer.csv")
# byte_level = df[df['Patch size'] == 1]
byte_level = df[(df['FLOPs'] == 's') & (df['Patch size'] == 2)]
# byte_level['Global transformer parameters'].sort_values(ascending=False)
fig = px.histogram(byte_level['Global model parameters'])

fig.show()

In [9]:
byte_level[(byte_level['Global model parameters'] <= 1.3e8) & (byte_level['Global model parameters'] >= 1.1e8) & (byte_level['Global model layers'] >= 15)]

,FLOPs,Patch size,Tokens,Encoder parameters,Global model parameters,Decoder parameters,Global model dimension,Encoder/Decoder dimension,Global model layers,Decoder layers
5249,s,4.0,1.050125e+10,3825664.00,1.228559e+08,11476992.00,832,640,15,3
5749,s,4.0,1.042370e+10,3098787.84,1.228559e+08,12395151.36,832,576,15,4
5809,s,4.0,1.198473e+10,2448424.96,1.117657e+08,9793699.84,768,512,16,4
5813,s,4.0,1.092582e+10,3098787.84,1.117657e+08,12395151.36,768,576,16,4
5886,s,4.0,1.153588e+10,2448424.96,1.188495e+08,9793699.84,768,512,17,4
5890,s,4.0,1.055154e+10,3098787.84,1.188495e+08,12395151.36,768,576,17,4
6016,s,4.0,1.187885e+10,2448424.96,1.117713e+08,9793699.84,704,512,19,4
6020,s,4.0,1.083775e+10,3098787.84,1.117713e+08,12395151.36,704,576,19,4
6081,s,4.0,1.150003e+10,2448424.96,1.164004e+08,9793699.84,704,512,20,4
6085,s,4.0,1.052154e+10,3098787.84,1.164004e+08,12395151.36,704,576,20,4
6357,s,4.0,1.062171e+10,2448424.96,1.228559e+08,12242124.80,832,512,15,5
6412,s,4.0,1.232431e+10,1874575.36,1.117657e+08,9372876.80,768,448,16,5
6416,s,4.0,1.114356e+10,2448424.96,1.117657e+08,12242124.80,768,512,16,5
6480,s,4.0,1.075448e+10,2448424.96,1.188495e+08,12242124.80,768,512,17,5
6595,s,4.0,1.221236e+10,1874575.36,1.117713e+08,9372876.80,704,448,19,5
6599,s,4.0,1.105196e+10,2448424.96,1.117713e+08,12242124.80,704,512,19,5
6653,s,4.0,1.181233e+10,1874575.36,1.164004e+08,9372876.80,704,448,20,5
6657,s,4.0,1.072331e+10,2448424.96,1.164004e+08,12242124.80,704,512,20,5
6713,s,4.0,1.041365e+10,2448424.96,1.223527e+08,12242124.80,704,512,21,5
6823,s,4.0,1.205758e+10,1874575.36,1.109565e+08,9372876.80,640,448,23,5
6827,s,4.0,1.092504e+10,2448424.96,1.109565e+08,12242124.80,640,512,23,5
6878,s,4.0,1.172720e+10,1874575.36,1.158758e+08,9372876.80,640,448,24,5
6882,s,4.0,1.065310e+10,2448424.96,1.158758e+08,12242124.80,640,512,24,5
6932,s,4.0,1.106012e+10,1874575.36,1.228559e+08,11247452.16,832,448,15,6
6936,s,4.0,9.955669e+09,2448424.96,1.228559e+08,14690549.76,832,512,15,6
6985,s,4.0,1.162709e+10,1874575.36,1.117657e+08,11247452.16,768,448,16,6
7041,s,4.0,1.120415e+10,1874575.36,1.188495e+08,11247452.16,768,448,17,6
7101,s,4.0,1.081091e+10,1874575.36,1.259333e+08,11247452.16,768,448,18,6
7154,s,4.0,1.152740e+10,1874575.36,1.117713e+08,11247452.16,704,448,19,6
7209,s,4.0,1.117033e+10,1874575.36,1.164004e+08,11247452.16,704,448,20,6
7264,s,4.0,1.083471e+10,1874575.36,1.223527e+08,11247452.16,704,448,21,6
7357,s,4.0,1.138939e+10,1874575.36,1.109565e+08,11247452.16,640,448,23,6
7407,s,4.0,1.109416e+10,1874575.36,1.158758e+08,11247452.16,640,448,24,6
7498,s,4.0,1.225073e+10,1377239.04,1.117713e+08,9640673.28,704,384,19,7
7502,s,4.0,1.091519e+10,1874575.36,1.117713e+08,13122027.52,704,448,19,7
7549,s,4.0,1.184822e+10,1377239.04,1.164004e+08,9640673.28,704,384,20,7
7553,s,4.0,1.059451e+10,1874575.36,1.164004e+08,13122027.52,704,448,20,7
7605,s,4.0,1.029214e+10,1874575.36,1.223527e+08,13122027.52,704,448,21,7
7692,s,4.0,1.209498e+10,1377239.04,1.109565e+08,9640673.28,640,384,23,7
7696,s,4.0,1.079138e+10,1874575.36,1.109565e+08,13122027.52,640,448,23,7
7740,s,4.0,1.176257e+10,1377239.04,1.158758e+08,9640673.28,640,384,24,7
7744,s,4.0,1.052597e+10,1874575.36,1.158758e+08,13122027.52,640,448,24,7
7786,s,4.0,1.101429e+10,1377239.04,1.223527e+08,11017912.32,704,384,21,8
7865,s,4.0,1.158801e+10,1377239.04,1.109565e+08,11017912.32,640,384,23,8
7912,s,4.0,1.128253e+10,1377239.04,1.158758e+08,11017912.32,640,384,24,8
7950,s,4.0,1.084013e+10,1377239.04,1.158758e+08,12395151.36,640,384,24,9

In [3]:
byte_level[(byte_level['Tokens'] >= 4.8e10)]

,FLOPs,Patch size,Tokens,Encoder parameters,Global model parameters,Decoder parameters,Global model dimension,Encoder/Decoder dimension,Global model layers,Decoder layers
0,s,2,6.312902e+10,344309.76,7498301.44,688619.52,448,192,4,2
118,s,2,5.509120e+10,344309.76,8263434.24,688619.52,384,192,6,2
264,s,2,5.450177e+10,344309.76,7651328.00,688619.52,320,192,8,2
334,s,2,4.937376e+10,344309.76,8607744.00,688619.52,320,192,9,2
1089,s,2,5.266842e+10,153026.56,7345274.88,612106.24,256,128,12,4
1441,s,2,5.133669e+10,153026.56,7345274.88,765132.80,256,128,12,5

4e18 FLOPs
===

Patch size = 2

1102: 4.9e10 tokens, 11M global model, 1.2M decoder, 384 global model dimension, 256 encoder/decoder dimension, 6 global model layers, 2 decoder layers

1421: 2.2e+10 tokens, 28M global model, 3M decoder, 512	global model dimension, 320	encoder/decoder dimension, 9 global model layers, 3 decoder layers

1487: 1.2e+10 tokens, 58M global model,	6M decoder, 704	global model dimension, 448	encoder/decoder dimension, 10 global model layers, 3 decoder layers

Patch size = 4

6e10 tokens, 19M global model,	1.8M decoder, 448 global model dimension, 256 encoder/decoder dimension, 8 global model layers,	3 decoder layers

2e+10 tokens, 59M global model,	5.5M decoder, 576 global model dimension, 384 encoder/decoder dimension, 15	global model layer, 4 decoder layer

1.2e+10	tokens, 120M global model, 9.8M decoder, 768 global model dimension, 512 encoder/decoder dimension, 17 global model layer, 4 decoder layer